/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import javax.accessibility.AccessibleContext;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JRootPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author david
 */
public class V_AfegirProducte extends javax.swing.JDialog {

    /**
     * Creates new form AfegirProducte
     */
    public V_AfegirProducte(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConfirmarCancelar = new javax.swing.ButtonGroup();
        afegirProducte_codi_textfield = new javax.swing.JTextField();
        afegirProducte_button = new javax.swing.JButton();
        afegir_cancelar_radiobutton = new javax.swing.JRadioButton();
        afegir_confirmar_radiobuton = new javax.swing.JRadioButton();
        afegirProducte_Dades_label1 = new javax.swing.JLabel();
        afegir_perible_checkbox = new javax.swing.JCheckBox();
        afegir_perible_label = new javax.swing.JLabel();
        afegirProducte_codi_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        afegir_dades_textarea = new javax.swing.JTextArea();
        afegirProducte_nom_label = new javax.swing.JLabel();
        afegirProducte_categoria_label = new javax.swing.JLabel();
        afegirProducte_nom_textfield = new javax.swing.JTextField();
        afegir_productePreu_textfield = new javax.swing.JTextField();
        Categoria_combobox = new javax.swing.JComboBox<>();
        afegir_producte_preu_label = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        FOTOfondojLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(afegirProducte_codi_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 116, -1));

        afegirProducte_button.setText("Afegir");
        getContentPane().add(afegirProducte_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 100, 40));

        ConfirmarCancelar.add(afegir_cancelar_radiobutton);
        afegir_cancelar_radiobutton.setForeground(new java.awt.Color(0, 0, 0));
        afegir_cancelar_radiobutton.setText("Cancelar");
        getContentPane().add(afegir_cancelar_radiobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        ConfirmarCancelar.add(afegir_confirmar_radiobuton);
        afegir_confirmar_radiobuton.setForeground(new java.awt.Color(0, 0, 0));
        afegir_confirmar_radiobuton.setText("Confirmar");
        getContentPane().add(afegir_confirmar_radiobuton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        afegirProducte_Dades_label1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        afegirProducte_Dades_label1.setForeground(new java.awt.Color(0, 0, 0));
        afegirProducte_Dades_label1.setText("Datos");
        getContentPane().add(afegirProducte_Dades_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        afegir_perible_checkbox.setForeground(new java.awt.Color(0, 0, 0));
        afegir_perible_checkbox.setText("Sí");
        getContentPane().add(afegir_perible_checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        afegir_perible_label.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        afegir_perible_label.setForeground(new java.awt.Color(0, 0, 0));
        afegir_perible_label.setText("Perible");
        getContentPane().add(afegir_perible_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        afegirProducte_codi_label.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        afegirProducte_codi_label.setForeground(new java.awt.Color(0, 0, 0));
        afegirProducte_codi_label.setText("Codigo:");
        getContentPane().add(afegirProducte_codi_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        afegir_dades_textarea.setColumns(20);
        afegir_dades_textarea.setRows(5);
        jScrollPane1.setViewportView(afegir_dades_textarea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 390, 90));

        afegirProducte_nom_label.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        afegirProducte_nom_label.setForeground(new java.awt.Color(0, 0, 0));
        afegirProducte_nom_label.setText("Nombre:");
        getContentPane().add(afegirProducte_nom_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        afegirProducte_categoria_label.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        afegirProducte_categoria_label.setForeground(new java.awt.Color(0, 0, 0));
        afegirProducte_categoria_label.setText("Categoria");
        getContentPane().add(afegirProducte_categoria_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        getContentPane().add(afegirProducte_nom_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 111, -1));

        afegir_productePreu_textfield.setText("       ");
        afegir_productePreu_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afegir_productePreu_textfieldActionPerformed(evt);
            }
        });
        getContentPane().add(afegir_productePreu_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 80, -1));

        Categoria_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(Categoria_combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 90, 21));

        afegir_producte_preu_label.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        afegir_producte_preu_label.setForeground(new java.awt.Color(0, 0, 0));
        afegir_producte_preu_label.setText("Precio:");
        getContentPane().add(afegir_producte_preu_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        Titulo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 0));
        Titulo.setText("Añadir Producto");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 290, 90));

        FOTOfondojLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        FOTOfondojLabel1.setForeground(new java.awt.Color(0, 0, 0));
        FOTOfondojLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Enfocado.jpg"))); // NOI18N
        FOTOfondojLabel1.setOpaque(true);
        getContentPane().add(FOTOfondojLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void afegir_productePreu_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afegir_productePreu_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_afegir_productePreu_textfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_AfegirProducte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_AfegirProducte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_AfegirProducte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_AfegirProducte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                V_AfegirProducte dialog = new V_AfegirProducte(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JComboBox<String> getCategoria_combobox() {
        return Categoria_combobox;
    }

    public void setCategoria_combobox(JComboBox<String> Categoria_combobox) {
        this.Categoria_combobox = Categoria_combobox;
    }

    public ButtonGroup getConfirmarCancelar() {
        return ConfirmarCancelar;
    }

    public void setConfirmarCancelar(ButtonGroup ConfirmarCancelar) {
        this.ConfirmarCancelar = ConfirmarCancelar;
    }

    public JLabel getFOTOfondojLabel1() {
        return FOTOfondojLabel1;
    }

    public void setFOTOfondojLabel1(JLabel FOTOfondojLabel1) {
        this.FOTOfondojLabel1 = FOTOfondojLabel1;
    }

    public JLabel getTitulo() {
        return Titulo;
    }

    public void setTitulo(JLabel Titulo) {
        this.Titulo = Titulo;
    }

    public JLabel getAfegirProducte_Dades_label1() {
        return afegirProducte_Dades_label1;
    }

    public void setAfegirProducte_Dades_label1(JLabel afegirProducte_Dades_label1) {
        this.afegirProducte_Dades_label1 = afegirProducte_Dades_label1;
    }

    public JButton getAfegirProducte_button() {
        return afegirProducte_button;
    }

    public void setAfegirProducte_button(JButton afegirProducte_button) {
        this.afegirProducte_button = afegirProducte_button;
    }

    public JLabel getAfegirProducte_categoria_label() {
        return afegirProducte_categoria_label;
    }

    public void setAfegirProducte_categoria_label(JLabel afegirProducte_categoria_label) {
        this.afegirProducte_categoria_label = afegirProducte_categoria_label;
    }

    public JLabel getAfegirProducte_codi_label() {
        return afegirProducte_codi_label;
    }

    public void setAfegirProducte_codi_label(JLabel afegirProducte_codi_label) {
        this.afegirProducte_codi_label = afegirProducte_codi_label;
    }

    public JTextField getAfegirProducte_codi_textfield() {
        return afegirProducte_codi_textfield;
    }

    public void setAfegirProducte_codi_textfield(JTextField afegirProducte_codi_textfield) {
        this.afegirProducte_codi_textfield = afegirProducte_codi_textfield;
    }

    public JLabel getAfegirProducte_nom_label() {
        return afegirProducte_nom_label;
    }

    public void setAfegirProducte_nom_label(JLabel afegirProducte_nom_label) {
        this.afegirProducte_nom_label = afegirProducte_nom_label;
    }

    public JTextField getAfegirProducte_nom_textfield() {
        return afegirProducte_nom_textfield;
    }

    public void setAfegirProducte_nom_textfield(JTextField afegirProducte_nom_textfield) {
        this.afegirProducte_nom_textfield = afegirProducte_nom_textfield;
    }

    public JRadioButton getAfegir_cancelar_radiobutton() {
        return afegir_cancelar_radiobutton;
    }

    public void setAfegir_cancelar_radiobutton(JRadioButton afegir_cancelar_radiobutton) {
        this.afegir_cancelar_radiobutton = afegir_cancelar_radiobutton;
    }

    public JRadioButton getAfegir_confirmar_radiobuton() {
        return afegir_confirmar_radiobuton;
    }

    public void setAfegir_confirmar_radiobuton(JRadioButton afegir_confirmar_radiobuton) {
        this.afegir_confirmar_radiobuton = afegir_confirmar_radiobuton;
    }

    public JTextArea getAfegir_dades_textarea() {
        return afegir_dades_textarea;
    }

    public void setAfegir_dades_textarea(JTextArea afegir_dades_textarea) {
        this.afegir_dades_textarea = afegir_dades_textarea;
    }

    public JCheckBox getAfegir_perible_checkbox() {
        return afegir_perible_checkbox;
    }

    public void setAfegir_perible_checkbox(JCheckBox afegir_perible_checkbox) {
        this.afegir_perible_checkbox = afegir_perible_checkbox;
    }

    public JLabel getAfegir_perible_label() {
        return afegir_perible_label;
    }

    public void setAfegir_perible_label(JLabel afegir_perible_label) {
        this.afegir_perible_label = afegir_perible_label;
    }

    public JTextField getAfegir_productePreu_textfield() {
        return afegir_productePreu_textfield;
    }

    public void setAfegir_productePreu_textfield(JTextField afegir_productePreu_textfield) {
        this.afegir_productePreu_textfield = afegir_productePreu_textfield;
    }

    public JLabel getAfegir_producte_preu_label() {
        return afegir_producte_preu_label;
    }

    public void setAfegir_producte_preu_label(JLabel afegir_producte_preu_label) {
        this.afegir_producte_preu_label = afegir_producte_preu_label;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

  

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Categoria_combobox;
    private javax.swing.ButtonGroup ConfirmarCancelar;
    private javax.swing.JLabel FOTOfondojLabel1;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel afegirProducte_Dades_label1;
    private javax.swing.JButton afegirProducte_button;
    private javax.swing.JLabel afegirProducte_categoria_label;
    private javax.swing.JLabel afegirProducte_codi_label;
    private javax.swing.JTextField afegirProducte_codi_textfield;
    private javax.swing.JLabel afegirProducte_nom_label;
    private javax.swing.JTextField afegirProducte_nom_textfield;
    private javax.swing.JRadioButton afegir_cancelar_radiobutton;
    private javax.swing.JRadioButton afegir_confirmar_radiobuton;
    private javax.swing.JTextArea afegir_dades_textarea;
    private javax.swing.JCheckBox afegir_perible_checkbox;
    private javax.swing.JLabel afegir_perible_label;
    private javax.swing.JTextField afegir_productePreu_textfield;
    private javax.swing.JLabel afegir_producte_preu_label;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
