/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

/**
 *
 * @author david
 */
public class V_Categoria extends javax.swing.JDialog {

    /**
     * Creates new form V_Categoria
     */
    public V_Categoria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoria_nom_textfield = new javax.swing.JTextField();
        confirmar_categoria_nom_button = new javax.swing.JButton();
        NomCategoria_Label = new javax.swing.JLabel();
        CategoriaTitulo1 = new javax.swing.JLabel();
        FOTOfondojLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        categoria_nom_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoria_nom_textfieldActionPerformed(evt);
            }
        });
        getContentPane().add(categoria_nom_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 180, -1));

        confirmar_categoria_nom_button.setText("Confirmar");
        getContentPane().add(confirmar_categoria_nom_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        NomCategoria_Label.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        NomCategoria_Label.setForeground(new java.awt.Color(0, 0, 0));
        NomCategoria_Label.setText("Nombre de la categoria");
        getContentPane().add(NomCategoria_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 180, 50));

        CategoriaTitulo1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        CategoriaTitulo1.setForeground(new java.awt.Color(0, 0, 0));
        CategoriaTitulo1.setText("Categorias");
        getContentPane().add(CategoriaTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 120, 50));

        FOTOfondojLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        FOTOfondojLabel1.setForeground(new java.awt.Color(0, 0, 0));
        FOTOfondojLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Enfocado.jpg"))); // NOI18N
        FOTOfondojLabel1.setOpaque(true);
        getContentPane().add(FOTOfondojLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categoria_nom_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoria_nom_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoria_nom_textfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                V_Categoria dialog = new V_Categoria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CategoriaTitulo1;
    private javax.swing.JLabel FOTOfondojLabel1;
    private javax.swing.JLabel NomCategoria_Label;
    private javax.swing.JTextField categoria_nom_textfield;
    private javax.swing.JButton confirmar_categoria_nom_button;
    // End of variables declaration//GEN-END:variables
}
