/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author david
 */
public class V_Main extends javax.swing.JFrame {

    /**
     * Creates new form V_Main
     */
    public V_Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo_label = new javax.swing.JLabel();
        Categoria_Label = new javax.swing.JLabel();
        Categorias_combobox = new javax.swing.JComboBox<>();
        afegirProducte_button = new javax.swing.JButton();
        eliminarProducte_button = new javax.swing.JButton();
        ModificarProductes_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        productes_table = new javax.swing.JTable();
        FOTOfondojLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo_label.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        Titulo_label.setForeground(new java.awt.Color(0, 0, 0));
        Titulo_label.setText("SUPERMERCADO");
        getContentPane().add(Titulo_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 320, 90));

        Categoria_Label.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Categoria_Label.setForeground(new java.awt.Color(0, 0, 0));
        Categoria_Label.setText("Categoria:");
        getContentPane().add(Categoria_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        Categorias_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(Categorias_combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 160, -1));

        afegirProducte_button.setText("Añadir");
        afegirProducte_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afegirProducte_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(afegirProducte_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 100, 30));

        eliminarProducte_button.setText("Eliminar");
        eliminarProducte_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProducte_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarProducte_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 100, 30));

        ModificarProductes_button.setText("Modificar");
        ModificarProductes_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarProductes_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(ModificarProductes_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, 100, 30));

        productes_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(productes_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 750, 150));

        FOTOfondojLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        FOTOfondojLabel1.setForeground(new java.awt.Color(0, 0, 0));
        FOTOfondojLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Enfocado.jpg"))); // NOI18N
        FOTOfondojLabel1.setOpaque(true);
        getContentPane().add(FOTOfondojLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarProductes_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarProductes_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarProductes_buttonActionPerformed

    private void eliminarProducte_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProducte_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarProducte_buttonActionPerformed

    private void afegirProducte_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afegirProducte_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_afegirProducte_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Main().setVisible(true);
            }
        });
    }

    public JLabel getCategoria_Label() {
        return Categoria_Label;
    }

    public void setCategoria_Label(JLabel Categoria_Label) {
        this.Categoria_Label = Categoria_Label;
    }

    public JComboBox<String> getCategorias_combobox() {
        return Categorias_combobox;
    }

    public void setCategorias_combobox(JComboBox<String> Categorias_combobox) {
        this.Categorias_combobox = Categorias_combobox;
    }

    public JLabel getFOTOfondojLabel1() {
        return FOTOfondojLabel1;
    }

    public void setFOTOfondojLabel1(JLabel FOTOfondojLabel1) {
        this.FOTOfondojLabel1 = FOTOfondojLabel1;
    }

    public JButton getModificarProductes_button() {
        return ModificarProductes_button;
    }

    public void setModificarProductes_button(JButton ModificarProductes_button) {
        this.ModificarProductes_button = ModificarProductes_button;
    }

    public JLabel getTitulo_label() {
        return Titulo_label;
    }

    public void setTitulo_label(JLabel Titulo_label) {
        this.Titulo_label = Titulo_label;
    }

    public JButton getAfegirProducte_button() {
        return afegirProducte_button;
    }

    public void setAfegirProducte_button(JButton afegirProducte_button) {
        this.afegirProducte_button = afegirProducte_button;
    }

    public JButton getEliminarProducte_button() {
        return eliminarProducte_button;
    }

    public void setEliminarProducte_button(JButton eliminarProducte_button) {
        this.eliminarProducte_button = eliminarProducte_button;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getProductes_table() {
        return productes_table;
    }

    public void setProductes_table(JTable productes_table) {
        this.productes_table = productes_table;
    }

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Categoria_Label;
    private javax.swing.JComboBox<String> Categorias_combobox;
    private javax.swing.JLabel FOTOfondojLabel1;
    private javax.swing.JButton ModificarProductes_button;
    private javax.swing.JLabel Titulo_label;
    private javax.swing.JButton afegirProducte_button;
    private javax.swing.JButton eliminarProducte_button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productes_table;
    // End of variables declaration//GEN-END:variables
}
