/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author david
 */
public class V_ModificarProducte extends javax.swing.JDialog {

    /**
     * Creates new form V_ModificarProducte
     */
    public V_ModificarProducte(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConfirmarCancelar = new javax.swing.ButtonGroup();
        modificarProd_Preu_textfield = new javax.swing.JTextField();
        modificarProd_nom_textfield = new javax.swing.JTextField();
        modificarProd_preu_label = new javax.swing.JLabel();
        modificarProd_button = new javax.swing.JButton();
        modificarProd_Dades_label1 = new javax.swing.JLabel();
        modificarPerible_checkbox = new javax.swing.JCheckBox();
        modificar_joc_titol_label = new javax.swing.JLabel();
        ModificarCodi_combobox = new javax.swing.JComboBox<>();
        modificar_producte_codi_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        modificarProdu_dades_textarea = new javax.swing.JTextArea();
        modificarProd_categoria_label = new javax.swing.JLabel();
        modificarProd_nom_label = new javax.swing.JLabel();
        modificarProducte_Categoria_combobox = new javax.swing.JComboBox<>();
        modificar_confirmar_radiobuton = new javax.swing.JRadioButton();
        modificar_cancelar_radiobutton = new javax.swing.JRadioButton();
        modificar_perible_label = new javax.swing.JLabel();
        ModificarTitulo = new javax.swing.JLabel();
        FOTOfondojLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modificarProd_Preu_textfield.setText("jTextField3");
        modificarProd_Preu_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProd_Preu_textfieldActionPerformed(evt);
            }
        });
        getContentPane().add(modificarProd_Preu_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 90, -1));

        modificarProd_nom_textfield.setText("jTextField2");
        getContentPane().add(modificarProd_nom_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 150, -1));

        modificarProd_preu_label.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        modificarProd_preu_label.setForeground(new java.awt.Color(0, 0, 0));
        modificarProd_preu_label.setText("Precio:");
        getContentPane().add(modificarProd_preu_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        modificarProd_button.setText("Aplicar");
        modificarProd_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProd_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(modificarProd_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 120, 40));

        modificarProd_Dades_label1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        modificarProd_Dades_label1.setForeground(new java.awt.Color(0, 0, 0));
        modificarProd_Dades_label1.setText("Datos:");
        getContentPane().add(modificarProd_Dades_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        modificarPerible_checkbox.setForeground(new java.awt.Color(0, 0, 0));
        modificarPerible_checkbox.setText("Sí");
        getContentPane().add(modificarPerible_checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        modificar_joc_titol_label.setFont(new java.awt.Font("Noto Mono", 0, 15)); // NOI18N
        modificar_joc_titol_label.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(modificar_joc_titol_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        ModificarCodi_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(ModificarCodi_combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 90, -1));

        modificar_producte_codi_label.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        modificar_producte_codi_label.setForeground(new java.awt.Color(0, 0, 0));
        modificar_producte_codi_label.setText("Codigo:");
        getContentPane().add(modificar_producte_codi_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 60, 20));

        modificarProdu_dades_textarea.setColumns(20);
        modificarProdu_dades_textarea.setRows(5);
        jScrollPane1.setViewportView(modificarProdu_dades_textarea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 360, 80));

        modificarProd_categoria_label.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        modificarProd_categoria_label.setForeground(new java.awt.Color(0, 0, 0));
        modificarProd_categoria_label.setText("Categoria");
        getContentPane().add(modificarProd_categoria_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        modificarProd_nom_label.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        modificarProd_nom_label.setForeground(new java.awt.Color(0, 0, 0));
        modificarProd_nom_label.setText("Nombre:");
        getContentPane().add(modificarProd_nom_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        modificarProducte_Categoria_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(modificarProducte_Categoria_combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 230, 30));

        ConfirmarCancelar.add(modificar_confirmar_radiobuton);
        modificar_confirmar_radiobuton.setForeground(new java.awt.Color(0, 0, 0));
        modificar_confirmar_radiobuton.setText("Confirmar");
        getContentPane().add(modificar_confirmar_radiobuton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        ConfirmarCancelar.add(modificar_cancelar_radiobutton);
        modificar_cancelar_radiobutton.setForeground(new java.awt.Color(0, 0, 0));
        modificar_cancelar_radiobutton.setText("Cancelar");
        getContentPane().add(modificar_cancelar_radiobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 412, -1, 30));

        modificar_perible_label.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        modificar_perible_label.setForeground(new java.awt.Color(0, 0, 0));
        modificar_perible_label.setText("Perecedero:");
        getContentPane().add(modificar_perible_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        ModificarTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        ModificarTitulo.setForeground(new java.awt.Color(0, 0, 0));
        ModificarTitulo.setText("Modificar Producto");
        getContentPane().add(ModificarTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 170, 40));

        FOTOfondojLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        FOTOfondojLabel1.setForeground(new java.awt.Color(0, 0, 0));
        FOTOfondojLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Enfocado.jpg"))); // NOI18N
        FOTOfondojLabel1.setOpaque(true);
        getContentPane().add(FOTOfondojLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarProd_Preu_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProd_Preu_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarProd_Preu_textfieldActionPerformed

    private void modificarProd_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProd_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarProd_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_ModificarProducte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_ModificarProducte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_ModificarProducte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_ModificarProducte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                V_ModificarProducte dialog = new V_ModificarProducte(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public ButtonGroup getConfirmarCancelar() {
        return ConfirmarCancelar;
    }

    public void setConfirmarCancelar(ButtonGroup ConfirmarCancelar) {
        this.ConfirmarCancelar = ConfirmarCancelar;
    }

    public JLabel getFOTOfondojLabel1() {
        return FOTOfondojLabel1;
    }

    public void setFOTOfondojLabel1(JLabel FOTOfondojLabel1) {
        this.FOTOfondojLabel1 = FOTOfondojLabel1;
    }

    public JComboBox<String> getModificarCodi_combobox() {
        return ModificarCodi_combobox;
    }

    public void setModificarCodi_combobox(JComboBox<String> ModificarCodi_combobox) {
        this.ModificarCodi_combobox = ModificarCodi_combobox;
    }

    public JLabel getModificarTitulo() {
        return ModificarTitulo;
    }

    public void setModificarTitulo(JLabel ModificarTitulo) {
        this.ModificarTitulo = ModificarTitulo;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JCheckBox getModificarPerible_checkbox() {
        return modificarPerible_checkbox;
    }

    public void setModificarPerible_checkbox(JCheckBox modificarPerible_checkbox) {
        this.modificarPerible_checkbox = modificarPerible_checkbox;
    }

    public JLabel getModificarProd_Dades_label1() {
        return modificarProd_Dades_label1;
    }

    public void setModificarProd_Dades_label1(JLabel modificarProd_Dades_label1) {
        this.modificarProd_Dades_label1 = modificarProd_Dades_label1;
    }

    public JTextField getModificarProd_Preu_textfield() {
        return modificarProd_Preu_textfield;
    }

    public void setModificarProd_Preu_textfield(JTextField modificarProd_Preu_textfield) {
        this.modificarProd_Preu_textfield = modificarProd_Preu_textfield;
    }

    public JButton getModificarProd_button() {
        return modificarProd_button;
    }

    public void setModificarProd_button(JButton modificarProd_button) {
        this.modificarProd_button = modificarProd_button;
    }

    public JLabel getModificarProd_categoria_label() {
        return modificarProd_categoria_label;
    }

    public void setModificarProd_categoria_label(JLabel modificarProd_categoria_label) {
        this.modificarProd_categoria_label = modificarProd_categoria_label;
    }

    public JLabel getModificarProd_nom_label() {
        return modificarProd_nom_label;
    }

    public void setModificarProd_nom_label(JLabel modificarProd_nom_label) {
        this.modificarProd_nom_label = modificarProd_nom_label;
    }

    public JTextField getModificarProd_nom_textfield() {
        return modificarProd_nom_textfield;
    }

    public void setModificarProd_nom_textfield(JTextField modificarProd_nom_textfield) {
        this.modificarProd_nom_textfield = modificarProd_nom_textfield;
    }

    public JLabel getModificarProd_preu_label() {
        return modificarProd_preu_label;
    }

    public void setModificarProd_preu_label(JLabel modificarProd_preu_label) {
        this.modificarProd_preu_label = modificarProd_preu_label;
    }

    public JTextArea getModificarProdu_dades_textarea() {
        return modificarProdu_dades_textarea;
    }

    public void setModificarProdu_dades_textarea(JTextArea modificarProdu_dades_textarea) {
        this.modificarProdu_dades_textarea = modificarProdu_dades_textarea;
    }

    public JComboBox<String> getModificarProducte_Categoria_combobox() {
        return modificarProducte_Categoria_combobox;
    }

    public void setModificarProducte_Categoria_combobox(JComboBox<String> modificarProducte_Categoria_combobox) {
        this.modificarProducte_Categoria_combobox = modificarProducte_Categoria_combobox;
    }

    public JRadioButton getModificar_cancelar_radiobutton() {
        return modificar_cancelar_radiobutton;
    }

    public void setModificar_cancelar_radiobutton(JRadioButton modificar_cancelar_radiobutton) {
        this.modificar_cancelar_radiobutton = modificar_cancelar_radiobutton;
    }

    public JRadioButton getModificar_confirmar_radiobuton() {
        return modificar_confirmar_radiobuton;
    }

    public void setModificar_confirmar_radiobuton(JRadioButton modificar_confirmar_radiobuton) {
        this.modificar_confirmar_radiobuton = modificar_confirmar_radiobuton;
    }

    public JLabel getModificar_joc_titol_label() {
        return modificar_joc_titol_label;
    }

    public void setModificar_joc_titol_label(JLabel modificar_joc_titol_label) {
        this.modificar_joc_titol_label = modificar_joc_titol_label;
    }

    public JLabel getModificar_perible_label() {
        return modificar_perible_label;
    }

    public void setModificar_perible_label(JLabel modificar_perible_label) {
        this.modificar_perible_label = modificar_perible_label;
    }

    public JLabel getModificar_producte_codi_label() {
        return modificar_producte_codi_label;
    }

    public void setModificar_producte_codi_label(JLabel modificar_producte_codi_label) {
        this.modificar_producte_codi_label = modificar_producte_codi_label;
    }

    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ConfirmarCancelar;
    private javax.swing.JLabel FOTOfondojLabel1;
    private javax.swing.JComboBox<String> ModificarCodi_combobox;
    private javax.swing.JLabel ModificarTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox modificarPerible_checkbox;
    private javax.swing.JLabel modificarProd_Dades_label1;
    private javax.swing.JTextField modificarProd_Preu_textfield;
    private javax.swing.JButton modificarProd_button;
    private javax.swing.JLabel modificarProd_categoria_label;
    private javax.swing.JLabel modificarProd_nom_label;
    private javax.swing.JTextField modificarProd_nom_textfield;
    private javax.swing.JLabel modificarProd_preu_label;
    private javax.swing.JTextArea modificarProdu_dades_textarea;
    private javax.swing.JComboBox<String> modificarProducte_Categoria_combobox;
    private javax.swing.JRadioButton modificar_cancelar_radiobutton;
    private javax.swing.JRadioButton modificar_confirmar_radiobuton;
    private javax.swing.JLabel modificar_joc_titol_label;
    private javax.swing.JLabel modificar_perible_label;
    private javax.swing.JLabel modificar_producte_codi_label;
    // End of variables declaration//GEN-END:variables
}
